config/routes.rb
Omrails::Application.routes.draw do

  resources :facturas

  resources :pins
  resources :empresas
  devise_for :usuarios , :path_prefix => 'my' do
    get "/usuarios/sign_out" => "devise/sessions#destroy", :as => :destroy_usuario_session
  end
  resources :usuarios

  get 'about' => 'pages#about'
  get 'ingresos' => 'facturas#ingresos'
  get 'new_ingreso' => 'facturas#new_ingresos'
  get 'egresos' => 'facturas#egresos'
  post 'upload' => 'facturas#upload'
  get 'dashboards' => 'facturas#dashboards'
  get '/conceptos/:id', :to => 'facturas#conceptos', :as => 'conceptos'

  get 'subir_facturas' => 'facturas#upload'

  root :to => 'pages#home'

end

app/models/pin.rb
require "paperclip"

class Pin < ActiveRecord::Base
  attr_accessible :description, :image


  validates :description, :presence => true
  validates :user_id, :presence => true
  validates_attachment 	:image, :presence => true, 
  						:content_type => { :content_type => [ 'image/jpeg' , 'image/jpg' , 'image/png' , 'image/gif' ] }

  has_attached_file :image, :styles => { :medium => "320x240>" }

  belongs_to :user

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # GET /pins

  before_filter :authenticate_user!, :except => :index
  def index
    @pins = Pin.find :all, :joins => [:user], :conditions => ["users.empresa_id = ?",current_user.empresa_id] 
    @compania = User.joins(:empresa).where("users.empresa_id = ?",current_user.empresa_id).select("companies.name").first
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pin.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pin.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pin.new(params[:pin])
    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, :notice => 'Pin was successfully created.' }
        format.json { render :json => @pin, :status => :created, :location => @pin }
      else
        format.html { render :action => "new" }
        format.json { render :json => @pin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pin.find(params[:id])
    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, :notice => 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @pin.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy_user
    @pin = current_user.pin.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  	<%=  f.input :image, :label => "Upload an image" %>
  	 <%= f.full_error :image_file_size, :class =>"alert alert-error" %>
  	<%= f.full_error :image_content_type, :class =>"alert alert-error" %>
    <%= f.input :description, :as => :text, :input_html => {:rows => "3"} %>
    <%= f.button :submit, :class => "btn btn-primary"%>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<center>
		<p>
		<%= link_to (image_tag pin.image(:medium)), pin %>
		<%= pin.description %>
		<br />
		<strong>
			Posted by <%= pin.user.name%>
		</strong>
		</p>

		<%= link_to 'Show', pin %>
		<% if current_user == pin.user %>
		|
		<%= link_to 'Edit', edit_pin_path(pin) %>
		|
		<%= link_to 'Destroy', pin, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
			<% end %>
	</center>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins">
  <h1>Lista de pins de <%= @compania.name%></h1>
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <center>
            <p>
            <%= image_tag @pin.image %>
        </p>
            <p>

              <%= @pin.description %>
            </p>
            <p>
              <%= @pin.user.name %>
            </p>
            <% if current_user == @pin.user %>
                <%= link_to 'Edit', edit_pin_path(@pin) %> |
            <% end %>
            <%= link_to 'Back', pins_path %>
        </center>
        </div>
    </div>
</div>