config/routes.rb
Omrails::Application.routes.draw do

  resources :facturas

  resources :pins
  resources :empresas
  devise_for :usuarios , :path_prefix => 'my' do
    get "/usuarios/sign_out" => "devise/sessions#destroy", :as => :destroy_usuario_session
  end
  resources :usuarios

  get 'about' => 'pages#about'
  get 'ingresos' => 'facturas#ingresos'
  get 'new_ingreso' => 'facturas#new_ingresos'
  get 'egresos' => 'facturas#egresos'
  post 'upload' => 'facturas#upload'
  get 'dashboards' => 'facturas#dashboards'
  get '/conceptos/:id', :to => 'facturas#conceptos', :as => 'conceptos'

  get 'subir_facturas' => 'facturas#upload'

  root :to => 'pages#home'

end

app/models/factura.rb
require "paperclip"

class Factura < ActiveRecord::Base
  # attr_accessible :title, :body

    attr_accessible :serie,:folio,:formaDePago,:metodoDePago,:numCtaPago,:lugarExpedicion,:anoAprobacion,:noCertificado,:nombre_emisor,:rfc_em,:nombre_receptor,:rfc_re,:total,:subTotal, :fechaExpedicion, :usuario_id,  :concepto_attributes, :archivo

  validates :serie, :presence => true
  validates :nombre_receptor, :presence => true
  validates :nombre_emisor, :presence => true
  validates :rfc_re, :presence => true
  validates :rfc_em, :presence => true
  validates :folio, :presence => true
  validates :formaDePago, :presence => true
  validates :metodoDePago, :presence => true
  validates :numCtaPago, :presence => true
  validates :lugarExpedicion, :presence => true
  validates :anoAprobacion, :presence => true
  validates :noCertificado, :presence => true
  validates :total, :presence => true
  validates :subTotal, :presence => true
  validates :fechaExpedicion, :presence => true

 has_attached_file :archivo



  validates :usuario_id, :presence => true
 


  belongs_to :usuario
  has_many :concepto
  accepts_nested_attributes_for :concepto
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
  before_filter :authenticate_usuario!, :except => :index

  def index
    @facturas = Factura.find :all, :joins => [:usuario], :conditions => ["usuarios.empresa_id = ?",current_usuario.empresa_id] 
    @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @facturas }
    end
  end

  def ingresos
    @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 
    @facturas = Factura.find :all, :joins => [:usuario], :conditions => ["usuarios.empresa_id = ? AND nombre_emisor = ?",current_usuario.empresa_id, @nombreEmpresa.first.name] 
  

    respond_to do |format|
      format.html # ingresos.html.erb
      format.json { render json: @factura }
    end
  end

  def egresos
   @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 
    @facturas = Factura.find :all, :joins => [:usuario], :conditions => ["usuarios.empresa_id = ? AND nombre_receptor = ?",current_usuario.empresa_id, @nombreEmpresa.first.name] 

    respond_to do |format|
      format.html # ingresos.html.erb
      format.json { render json: @factura }
    end
  end

  def upload
    @factura = Factura.new
    @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 

    respond_to do |format|
      format.html # ingresos.html.erb
      format.json { render json: @factura }
    end
  end
  # GET /facturas/1
  # GET /facturas/1.json
  def conceptos
    @factura = Factura.find(params[:id])
    @conceptos = Concepto.find :all, :joins => [:factura], :conditions => ["conceptos.factura_id = ?",params[:id]] 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factura }
    end
  end


  # GET /facturas/1
  # GET /facturas/1.json
  def show
    @factura = Factura.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @factura }
    end
  end

  # GET /facturas/new
  # GET /facturas/new.json
  def new
    @factura = Factura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factura }
    end
  end

    # GET /facturas/new
  # GET /facturas/new.json
  def new_ingresos
    @factura = Factura.new
    @factura.concepto.build
    
    @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factura }
    end
  end

  # GET /facturas/1/edit
  def edit
    @factura = Factura.find(params[:id])
  end

  # POST /facturas
  # POST /facturas.json
  def create
    @factura = Factura.new(params[:factura])

    respond_to do |format|
      if @factura.save
        format.html { redirect_to @factura, notice: 'Factura was successfully created.' }
        format.json { render json: @factura, status: :created, location: @factura }
      else
        format.html { render action: "new" }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facturas/1
  # PUT /facturas/1.json
  def update
    @factura = Factura.find(params[:id])

    respond_to do |format|
      if @factura.update_attributes(params[:factura])
        format.html { redirect_to @factura, notice: 'Factura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @factura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facturas/1
  # DELETE /facturas/1.json
  def destroy
    @factura = Factura.find(params[:id])
    @factura.destroy

    respond_to do |format|
      format.html { redirect_to facturas_url }
      format.json { head :no_content }
    end
  end

  def upload
    @factura = Factura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @factura }
    end
  end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/_concepto_fields.erb
<tr>
    <td colspan="3"><b>Conceptos de la factura</b></td>
         

</tr>
<tr>
	<td><%=  f.input :cantidad, :label => "Cantidad"  %></td>
	<td><%=  f.input :producto, :label => "Producto"  %></td>
		<td><%=  f.input :unidad, :label => "Unidad"  %></td>

	<td><%=  f.input :precio_unitario, :label => "Precio unitario"  %></td>

</tr>

<tr>
		<td><%=  f.input :importe, :label => "Importe"  %></td>
	<td><%=  f.input :impuesto, :label => "Impuesto"  %></td>
		<td><%=  f.input :total, :label => "Total"  %></td>

app/views/facturas/_form.html.erb
	<%= simple_form_for(@factura, :html => {:class => "form-horizontal"}) do |f| %>
		<%= f.error_notification %>
			<div class="form-inputs">
			  	<%=  f.input :serie, :label => "Serie", :as => :hidden,  :input_html => { :value => "FQUQUE" } %>
			   	<%=  f.input :folio, :label => "Folio", :as => :hidden,  :input_html => { :value => "80424" } %>
			   	<%=  f.input :formaDePago, :label => "Forma de pago", :as => :hidden,  :input_html => { :value => "Pago en una sola exhibición" } %>
			  	<%=  f.input :metodoDePago, :label => "Método de pago", :as => :hidden,  :input_html => { :value => "TARJETA DE CREDITO" } %>
			   	<%=  f.input :numCtaPago, :label => "Número de Cuenta", :as => :hidden,  :input_html => { :value => "Ultimos Cuatro Digitos : 6793" } %>
			   	<%=  f.input :lugarExpedicion, :label => "Lugar de expedición", :as => :hidden,  :input_html => { :value => "Queretaro, Mexico" } %>
			   	<%=  f.input :anoAprobacion, :label => "Año de aprobación", :as => :hidden,  :input_html => { :value => "2009" } %>
			   	<%=  f.input :noCertificado, :label => "Numero de certificado", :as => :hidden,  :input_html => { :value => "203321592" } %>
			   	<%=  f.input :nombre_emisor, :label => "Nombre del emisor"%>
			   	<%=  f.input :rfc_em, :label => "RFC del emisor" %>
			   	<%=  f.input :nombre_receptor, :label => "Nombre del receptor" %>
			   	<%=  f.input :rfc_re, :label => "RFC del receptor" %>
			   	<%=  f.input :total, :label => "total" %>
				<%=  f.input :subTotal, :label => "subTotal" %>
				<%=  f.input :usuario_id, :label => "Id de usuario", :as => :hidden,  :input_html => { :value => current_usuario.id } %>
				<%=  f.input :fechaExpedicion, :label => "Fecha y hora de expedicion", :width => "10px" %>
			</div>
		<div class="form-actions">
			<%= f.button :submit %>
		</div>
	<% end %>

app/views/facturas/_formegresos.erb
	<%= simple_form_for(@factura, :html => {:class => "form-horizontal"}) do |f| %>
		<%= f.error_notification %>
			<div class="form-inputs">
			  	<%=  f.input :serie, :label => "Serie", :as => :hidden,  :input_html => { :value => "FQUQUE" } %>
			   	<%=  f.input :folio, :label => "Folio", :as => :hidden,  :input_html => { :value => "80424" } %>
			   	<%=  f.input :formaDePago, :label => "Forma de pago", :as => :hidden,  :input_html => { :value => "Pago en una sola exhibición" } %>
			  	<%=  f.input :metodoDePago, :label => "Método de pago", :as => :hidden,  :input_html => { :value => "TARJETA DE CREDITO" } %>
			   	<%=  f.input :numCtaPago, :label => "Número de Cuenta", :as => :hidden,  :input_html => { :value => "Ultimos Cuatro Digitos : 6793" } %>
			   	<%=  f.input :lugarExpedicion, :label => "Lugar de expedición", :as => :hidden,  :input_html => { :value => "Queretaro, Mexico" } %>
			   	<%=  f.input :anoAprobacion, :label => "Año de aprobación", :as => :hidden,  :input_html => { :value => "2009" } %>
			   	<%=  f.input :noCertificado, :label => "Numero de certificado", :as => :hidden,  :input_html => { :value => "203321592" } %>
			   	<%=  f.input :nombreEmisor, :label => "Nombre del emisor" %>
			   	<%=  f.input :rfcEm, :label => "RFC del emisor" %>
			   	<%=  f.input :nombreReceptor, :label => "Nombre del receptor", :readonly => true,  :input_html => { :value => @empresaNombre.first.name } %>
			   	<%=  f.input :rfcRe, :label => "RFC del receptor", :readonly => true,  :input_html => { :value => @empresaNombre.first.rfc } %>
			   	<%=  f.input :total, :label => "total" %>
				<%=  f.input :subTotal, :label => "subTotal" %>
				<%=  f.input :usuario_id, :label => "Id de usuario", :as => :hidden,  :input_html => { :value => current_usuario.id } %>
				<%=  f.input :fechaExpedicion, :label => "Fecha y hora de expedicion", :width => "10px" %>
			</div>
		<div class="form-actions">
			<%= f.button :submit %>
		</div>
	<% end %>

app/views/facturas/_formingresos.erb
	<%= simple_form_for(@factura, :html => {:class => "form-horizontal"}) do |f| %>
		<%= f.error_notification %>
		<div style="width:500px">
			<div class="form-inputs" style="widtd:500px">
			  	<%=  f.input :nombre_emisor, :label => "Nombre del emisor", :readonly => true,  :input_html => { :value => @nombreEmpresa.first.name } %>
			   	<%=  f.input :rfc_em, :label => "RFC del emisor" , :readonly => true,  :input_html => { :value => @nombreEmpresa.first.rfc }%>
			   	<%=  f.input :nombre_receptor, :label => "Nombre del receptor" %>
			   	<%=  f.input :rfc_re, :label => "RFC del receptor" %>

			  	<%=  f.input :serie, :label => "Serie" %>
			   	<%=  f.input :folio, :label => "Folio" %>
			   	<%=  f.input :formaDePago, :label => "Forma de pago" %>
			  	<%=  f.input :metodoDePago, :label => "Método de pago" %>
			   	<%=  f.input :numCtaPago, :label => "Número de Cuenta" %>
			   	<%=  f.input :lugarExpedicion, :label => "Lugar de expedición" %>
			   	<%=  f.input :anoAprobacion, :label => "Año de aprobación"  %>
			   	<%=  f.input :noCertificado, :label => "Numero de certificado"  %>
			   	
			   	<%=  f.input :total, :label => "total" %>
				<%=  f.input :subTotal, :label => "subTotal" %>
				<%=  f.input :usuario_id, :label => "Id de usuario", :as => :hidden,  :input_html => { :value => current_usuario.id } %>
				<%=  f.input :fechaExpedicion, :label => "Fecha y hora de expedicion", :widtd => "10px" %>
			</div>
			</div>
			<div >
			<table class="table" style="width:500px">

				  <%= f.simple_fields_for :concepto do |builder| %>
					  <%= render 'concepto_fields', :f => builder %>
				  <% end %>
			</table>
					<p><%= link_to_add_fields "Agregar concepto", f, :concepto %></p>
					</div>
		<div class="form-actions">
			<%= f.button :submit %>
		</div>
	<% end %>

app/views/facturas/dashboards.erb
<% facturas_array = Array.new(12,0) %>
<% 
@egresos = 0
@ingresos = 0
    @facturas = Factura.find :all, :joins => [:usuario], :conditions => ["usuarios.empresa_id = ?",current_usuario.empresa_id] 
    @nombreEmpresa = Empresa.find :all, :conditions => ["id = ?",current_usuario.empresa_id] 

%>
<% @facturas.each do |factura| %>
    <% if factura.nombre_emisor == @nombreEmpresa.first.name%>
        <% facturas_array[factura.fechaExpedicion.month - 1]+=factura.total    %>
        <% @egresos += factura.total%>
        <% else %>
            <% @ingresos += factura.total%>
    <% end %>
<% end %>
<script type="text/javascript">
    document.getElementById('tabla').onclick = function() {
        alert('Hey!');
    }
</script>
<script type="text/javascript">
$(function () {
        $('#container1').highcharts({
            chart: {
                type: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: {
                text: 'Ventas por mes',
                x: -20 //center
            },
            subtitle: {
                text: 'Source: WorldClimate.com',
                x: -20
            },
            xAxis: {
                categories: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
                    'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
            },
            yAxis: {
                title: {
                    text: 'Pesos Mexicanos'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valuePrefix: '$'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [{
                name: 'Ventas por mes',
                data: <%= facturas_array %>
            }]
        });
    });
    

    </script>
<script type="text/javascript">
  
  $(function () { 
    $('#container2').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Egresos vs. Ingresos'
        },
        series: [{
                type: 'pie',
                data: [
                    ['Egresos',   <%= @egresos %>],
                    ['Ingresos', <%= @ingresos %>],
                ]
            }]
    });})
</script>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#facturas_charts').highcharts({
      chart: {
        type: "bar"
      },
      title: {
        text: "Orders by Day"
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "Dollars"
        }
      },
      series: [{

        data: [1,2,5,7,3]
      }]
    });
  });
</script>


<div class="container">
<h1>Listing facturas</h1>

<center>
<div class="row-fluid">
    <div class="span4"></div>
    <div class="span8">       
    </div>
</div>
    <div class="row">
            <div class="span3 bs-docs-sidebar">
                <ul class="nav nav-list bs-docs-sidenav">
                    <li><a id="submenu" class="submenu" href="#grafica1"  ><i class="icon-chevron-right"></i> Venta por mes</a></li>
                    <li><a id="submenu" class="submenu" href="#grafica2"><i class="icon-chevron-right"></i> Egresos vs. Ingresos</a></li>
                </ul>
            </div>
        <div class="span9">

            <!-- Download
        ================================================== -->
            <section id="grafica1" class="docs">
                <div class="page-header">
                    <h3>1. Venta por mes</h3>
                </div>
                <p>
                    <div id="container1" ></div>  
                </p>
            </section>
            <!-- File structure
        ================================================== -->
            <section id="grafica2" class="docs">
                <div class="page-header">
                    <h3>2. Egresos vs. Ingresos</h3>
                </div>
                <p>
                    <div id="container2" ></div>  
                </p>
            </section>
 
           
        </div>
    </div>




<br />
</center>
</div>
<%= link_to 'New Factura', new_factura_path %>

app/views/facturas/edit.html.erb
<h1>Editing factura</h1>

<%= render 'form' %>

<%= link_to 'Show', @factura %> |
<%= link_to 'Back', facturas_path %>

app/views/facturas/egresos.erb
<script type="text/javascript">
$(document).ready(function(){
                $.datepicker.regional[""].dateFormat = 'dd/mm/yy';
                $.datepicker.setDefaults($.datepicker.regional['']);
     $('#example').dataTable({
        "aoColumns": [ 
             { "sWidth": "200px" },
            null,
            null,
            null,
            null       ]
    } ).columnFilter({ sPlaceHolder: "head:before",
            aoColumns: [ { type: "date-range", sRangeFormat: "Between {from} and {to} dates" },
                     { type: "text" },
                                     { type: "text"  },
                                     { type: "text"  },
                                      { type: "number-range" }
                ]

        });
});



        </script>

<body>
                         
<center>
<div style="width:900px">
    <%  @empresaNombre = Empresa.find :all, :conditions => ["id = ?", current_usuario.empresa.id]   
    @suma = 0%>
    <div id="container">
    <h1>Tabla de facturas de egresos</h1>
        <div id="containerTabla" >                                      
            <div id="demo">
                <table id="example" class="display">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Identificador de la factura</th>
                            <th>Proveedor</th>
                            <th>RFC del proovedor</th>
                            <th>Total</th>
                            <th></th>
                            <th></th>
                        </tr>
                        <tr>
                            <th>Fecha</th>
                            <th>Identificador de la factura</th>
                            <th>Proveedor</th>
                            <th>RFC del proovedor</th>
                            <th>Total</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                    <% @facturas.each do |factura| %>
                        <tr>
                            <% faux = factura.created_at.to_s.split(" ")
                                fecha = faux[0]
                                fecha2 = fecha.split("-")
                                fecha = fecha2[2]+"/"+fecha2[1]+"/"+fecha2[0]
                             %>
                            <td><%= fecha %></td>                          
                            <td><%= factura.folio %></td>
                            <td><%= factura.nombre_emisor %></td>
                            <td><%= factura.rfc_em %></td>
                            <td><%= factura.total %></td>
                            <td><%= link_to 'Show', conceptos_path(factura) %></td>
                            <td><%= link_to 'Destroy', factura, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
                            <% @suma += factura.total %>
                            
                        </tr>
                    <% end %>
                    
                    </tbody>
                    <tfoot>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>Total</th>
                        <th><%= @suma %></th>
                        <th></th>
                        <th></th>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>  
</div></center>
<%= link_to 'Back', facturas_path %>
<br/><br/>

app/views/facturas/index.html.erb
<% facturas_array = Array.new(12,0) %>
<% 
@egresos = 0
@ingresos = 0
%>
<% @facturas.each do |factura| %>
    <% if factura.nombre_emisor == @nombreEmpresa.first.name%>
        <% facturas_array[factura.fechaExpedicion.month - 1]+=factura.total    %>
        <% @egresos += factura.total%>
        <% else %>
            <% @ingresos += factura.total%>
    <% end %>
<% end %>
<script type="text/javascript">
    document.getElementById('tabla').onclick = function() {
        alert('Hey!');
    }
</script>
<script type="text/javascript">
$(function () {
        $('#container1').highcharts({
            chart: {
                type: 'line',
                marginRight: 130,
                marginBottom: 25
            },
            title: {
                text: 'Ventas por mes',
                x: -20 //center
            },
            subtitle: {
                text: 'Source: WorldClimate.com',
                x: -20
            },
            xAxis: {
                categories: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun',
                    'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
            },
            yAxis: {
                title: {
                    text: 'Pesos Mexicanos'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                valuePrefix: '$'
            },
            legend: {
                layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -10,
                y: 100,
                borderWidth: 0
            },
            series: [{
                name: 'Ventas por mes',
                data: <%= facturas_array %>
            }]
        });
    });
    

    </script>
<script type="text/javascript">
  
  $(function () { 
    $('#container2').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Egresos vs. Ingresos'
        },
        series: [{
                type: 'pie',
                data: [
                    ['Egresos',   <%= @egresos %>],
                    ['Ingresos', <%= @ingresos %>],
                ]
            }]
    });})
</script>

<script type="text/javascript" charset="utf-8">
  $(function() {
    $('#facturas_charts').highcharts({
      chart: {
        type: "bar"
      },
      title: {
        text: "Orders by Day"
      },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "Dollars"
        }
      },
      series: [{

        data: [1,2,5,7,3]
      }]
    });
  });
</script>


<div class="container">
<h1>Listing facturas</h1>

<center>
<div class="row-fluid">
    <div class="span4"></div>
    <div class="span8">       
    </div>
</div>
    <div class="row">

        <div>


                    <!-- Tabla de facturas
        ================================================== -->
            <section id="tabla" class="doc">
                <div class="page-header">
                    <h3>1. Tabla de facturas</h3>
                </div>
                <p>
                    <div id="containerTabla" >                
                        <table class="table">
                          <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                          </tr>

                        <% @facturas.each do |factura| %>
                          <tr>
                            <td><%= factura.nombre_emisor %></td>
                            <td><%= factura.nombre_receptor %></td>
                            <td><%= factura.total %></td>
                            <td><%= link_to 'Show', conceptos_path(factura) %></td>
                            <td><%= link_to 'Edit', conceptos_path(factura) %></td>
                            <td><%= link_to 'Destroy', factura, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                        </table>
                    </div>  
                </p>
            </section>
        
 
           
        </div>
    </div>




<br />
</center>
</div>
<%= link_to 'New Factura', new_factura_path %>

app/views/facturas/new.html.erb
<center><div >

<h1>Nueva factura</h1>
<%= render 'form' %>
</div></center>
<%= link_to 'Back', facturas_path %>

app/views/facturas/new_egresos.html.erb
<center><div >

<h1>Nueva factura</h1>
<%= render 'formegresos' %>
</div></center>
<%= link_to 'Back', facturas_path %>

app/views/facturas/new_ingresos.html.erb
<script>
	function displayResult()
	{
		var table=document.getElementById("myTable");
		var row=table.insertRow(0);
		var cell1=row.insertCell(0);
		var cell2=row.insertCell(1);
		cell1.innerHTML="New";
		cell2.innerHTML="New";
	}
</script>
<center><div>

<h1>Nueva factura</h1>
<%= render 'formingresos' %>


</div></center>
<%= link_to 'Back', facturas_path %>

app/views/facturas/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_factura_path(@factura) %> |
<%= link_to 'Back', facturas_path %>

app/views/facturas/upload.erb
<center><div style="width:500px">
    <%  @empresaNombre = Empresa.find :all, :conditions => ["id = ?", current_usuario.empresa.id]   %>

<h1>Subir factura</h1>
	<h3>Zona en construcción</h3>
<%= simple_form_for @factura, :url => upload_path, :html => {:class => "form-horizontal"} do |form| %>
  <%= form.input :archivo %>
      <%= form.button :submit, :class => "btn btn-primary"%>

<% end %>
	<div id="widgets"></div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
    $("#widgets").jTable({
      columns: [
        {heading: "Column 1", attribute: "attribute_1"},
        {heading: "Column 2", attribute: "attribute_2"},
        {heading: "Column 3", attribute: "attribute_3"}
      ]
    })
  })
</script>
</div></center>
<%= link_to 'Back', facturas_path %>