config/routes.rb
Omrails::Application.routes.draw do

  resources :facturas

  resources :pins
  resources :empresas
  devise_for :usuarios , :path_prefix => 'my' do
    get "/usuarios/sign_out" => "devise/sessions#destroy", :as => :destroy_usuario_session
  end
  resources :usuarios

  get 'about' => 'pages#about'
  get 'ingresos' => 'facturas#ingresos'
  get 'new_ingreso' => 'facturas#new_ingresos'
  get 'egresos' => 'facturas#egresos'
  post 'upload' => 'facturas#upload'
  get 'dashboards' => 'facturas#dashboards'
  get '/conceptos/:id', :to => 'facturas#conceptos', :as => 'conceptos'

  get 'subir_facturas' => 'facturas#upload'

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row">
			<div class="span3">
				<div class="widget">
					<h5>Browse pages</h5>
					<ul class="regular">
						<li><a href="#">Work for us</a></li>
						<li><a href="#">Creative process</a></li>
						<li><a href="#">Case study</a></li>
						<li><a href="#">Scaffold awwards</a></li>
						<li><a href="#">Meet the team</a></li>
					</ul>
				</div>
			</div>
			<div class="span3">
				<div class="widget">
					<h5>Recent blog posts</h5>
					<ul class="regular">
						<li><a href="#">Lorem ipsum dolor sit amet</a></li>
						<li><a href="#">Mea malis nominavi insolens ut</a></li>
						<li><a href="#">Minim timeam has no aperiri sanctus ei mea per pertinax</a></li>
						<li><a href="#">Te malorum dignissim eos quod sensibus</a></li>
					</ul>
				</div>
			</div>
			<div class="span3">
				<div class="widget">
					
				</div>
			</div>
			<div class="span3">
				<div class="widget">
					<!-- logo -->
					<a class="brand logo" href="index.html">
					<img src="assets/img/logo-dark.png" alt="" />
					</a>
					<!-- end logo -->
					<address>
					<strong>TEGIK de SA</strong><br>
					 Garza Sada, L 21-22<br>
					 Monterrey, Nuevo León<br>
					<abbr title="Phone">P:</abbr> (81) 1771.8845 </address>
				</div>
			</div>
		</div>
	</div>
	<div class="verybottom">
		<div class="container">
			<div class="row">
				<div class="span6">
					<p>
						&copy; Serenity 2013 - All right reserved
					</p>
				</div>
				<div class="span6">
					<p class="pull-right">
						Designed by <a href="http://iweb-studio.com">iWebStudio</a>
					</p>
				</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="navbar navbar-fixed-top">
	    <div class="navbar-inner">
		    <div class="container">    
		    	<%= link_to image_tag("logo.png", :class => 'brand logo'), root_path %>
			    <div class="navigation">
    				<nav>
					<ul class="nav topnav">
					    <!-- Be sure to leave the brand out there if you want it shown -->

					    <li class="dropdown active">

					    </li> 

					    <!-- Everything you want hidden at 940px or less, place within here -->
					    <li class="nav-collapse collapse">
					    	
					    	<% if usuario_signed_in? %>
					    		<ul class="nav pull-right">
						    		<% if can? :dashboard, @usuario %>
						    			<li><%= link_to  "Dashboard", dashboards_path%> </li>
						    		<% end %>


						    		<% if can? :facturas, @usuario %>
						    			<li><%= link_to  "Ingresos", ingresos_path%> </li>
						    		<% end %>
						    		<% if can? :facturas, @usuario %>
						    			<li><%= link_to  "Egresos", egresos_path%> </li>
						    		<% end %>
						    		<% if can? :facturas, @usuario %>
						    			<li><%= link_to  "Subir facturas", subir_facturas_path%> </li>
						    		<% end %>
						    		<% if can? :usuarioadmon, @usuario %>
						    			<li><%= link_to  "User Management", usuarios_path%> </li>
						    		<% end %>
					    		

						    		<li><%= link_to  "Edit profile", edit_usuario_registration_path%> </li>
						    		<li><%= link_to  "Log out", destroy_usuario_session_path, :method => 'delete'%> </li>
								

							<% else %>
							<ul class="nav">
								<li><%= link_to  "About", about_path %></li>
					    	</ul >
					    	<ul class="nav pull-right">
								<li><%= link_to  "Login", new_usuario_session_path %> </li>
					    	</ul>
							<% end %>
					    	</ul>
				    <!-- .nav, .navbar-search, .navbar-form, etc -->
				    	</li>


				    </ul>
				    </nav>
			    </div>
		    </div>
	    </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Omrails</title>

  <%= csrf_meta_tag %>



	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag 'jquery.min.js',
'jquery_ujs', "rails","application", "highcharts", "exporting"%>
	
  	
</head>
<body>
	<%= render 'layouts/header' %>
		<% flash.each do |name,msg| %>
			<%= content_tag(:div, msg, :class => "alert alert-#{name}") %>
		<% end %> 
		<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>